export const RANDOMIZE_LIST = 'RANDOMIZE_LIST'
export const START_BUBBLE_SORT = 'START_BUBBLE_SORT';
export const SORTING_START = 'SORTING_START';
export const SORTING_END = 'SORTING_END';
export const CLEAN_LIST = 'CLEAN_LIST';
export const SORTING_PAUSE = 'SORTING_PAUSE';
export const SORTING_RESTART = 'SORTING_RESTART';

export const UPDATE_LIST = 'UPDATE_LIST';

export const SPEED_CHANGE = 'SPEED_CHANGE';

export const STOP_SORTING = 'STOP_SORTING';